name: Build Docker Image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  IMAGE_NAME: wsi_neudeg

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GITLAB_REGISTRY }}
          username: ${{ secrets.GITLAB_REGISTRY_TOKEN_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN_PASSWORD }}

      - name: Build and push clam image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:clam

      - name: Build and push bftools image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.bftools
          push: true
          tags: ${{ vars.GITLAB_REGISTRY }}/${{ env.IMAGE_NAME }}:bftools
